*;
*MOST FREQUENT VALUE (COUNT);
*;
label IMP_num_of_doors = 'Imputed: num-of-doors';
IMP_num_of_doors = num_of_doors;
if missing(num_of_doors) then IMP_num_of_doors = 4;
*;
*MEAN-MAX-MIN-MEDIAN-MIDRANGE AND ROBUST ESTIMATES;
*;
format IMP_bore BEST12.0;
label IMP_bore = 'Imputed bore';
IMP_bore = bore;
if missing(bore) then IMP_bore = 3.3026530612;
format IMP_price BEST12.0;
label IMP_price = 'Imputed price';
IMP_price = price;
if missing(price) then IMP_price = 12773.191919;
format IMP_stroke BEST12.0;
label IMP_stroke = 'Imputed stroke';
IMP_stroke = stroke;
if missing(stroke) then IMP_stroke = 3.2513265306;
*;
*INDICATOR VARIABLES;
*;
label M_bore = "Imputation Indicator for bore";
if missing(bore) then M_bore = 1;
else M_bore= 0;
label M_num_of_doors = "Imputation Indicator for num_of_doors";
if missing(num_of_doors) then M_num_of_doors = 1;
else M_num_of_doors= 0;
label M_price = "Imputation Indicator for price";
if missing(price) then M_price = 1;
else M_price= 0;
label M_stroke = "Imputation Indicator for stroke";
if missing(stroke) then M_stroke = 1;
else M_stroke= 0;
