if NAME="Risk" then do;
ROLE="TARGET";
LEVEL="BINARY";
ORDER="";
end;
if NAME="aspiration" then do;
ROLE="INPUT";
LEVEL="NOMINAL";
ORDER="";
end;
if NAME="engine_location" then do;
ROLE="INPUT";
LEVEL="NOMINAL";
ORDER="";
end;
if NAME="fuel_type" then do;
ROLE="INPUT";
LEVEL="NOMINAL";
ORDER="";
end;
if NAME="normalized_losses" then do;
ROLE="REJECTED";
LEVEL="INTERVAL";
ORDER="";
end;
if NAME="num_of_doors" then do;
ROLE="INPUT";
LEVEL="NOMINAL";
ORDER="";
end;
if NAME="symboling" then do;
ROLE="REJECTED";
LEVEL="NOMINAL";
ORDER="";
end;
drop DROP;
