if ROLE in('INPUT', 'REJECTED') then do;
if upcase(NAME) in(
'IMP_BORE'
'IMP_HORSEPOWER'
'IMP_NUM_OF_DOORS'
'IMP_PEAK_RPM'
'IMP_PRICE'
'IMP_STROKE'
'ASPIRATION'
'BODY_STYLE'
'CITY_MPG'
'COMPRESSION_RATIO'
'CURB_WEIGHT'
'DRIVE_WHEELS'
'ENGINE_SIZE'
'ENGINE_TYPE'
'FUEL_SYSTEM'
'FUEL_TYPE'
'HEIGHT'
'HIGHWAY_MPG'
'LENGTH'
'NUM_OF_CYLINDERS'
'WHEEL_BASE'
'WIDTH'
) then ROLE='INPUT';
else delete;
end;
