if ROLE in('INPUT', 'REJECTED') then do;
if upcase(NAME) in(
'IMP_NUM_OF_DOORS'
'REP_IMP_BORE'
'REP_IMP_PRICE'
'REP_IMP_STROKE'
'REP_CITY_MPG'
'REP_COMPRESSION_RATIO'
'REP_CURB_WEIGHT'
'REP_ENGINE_SIZE'
'REP_HEIGHT'
'REP_HIGHWAY_MPG'
'REP_HORSEPOWER'
'REP_LENGTH'
'REP_PEAK_RPM'
'REP_WHEEL_BASE'
'REP_WIDTH'
'ASPIRATION'
'BODY_STYLE'
'DRIVE_WHEELS'
'ENGINE_TYPE'
'FUEL_SYSTEM'
'FUEL_TYPE'
'NUM_OF_CYLINDERS'
) then ROLE='INPUT';
else delete;
end;
